language: python
python:
  - "3.7"
install:
  - pip install -r requirements.txt
  - pip install codecov

# Run the unit test
script:
  - pytest --doctest-modules --junitxml=junit/test-results.xml --cov=hacker_rank --cov-report=xml --cov-report=html

# Push the results back to codecov
after_success:
  - codecov