language: python
sudo: false
python:
  - "3.7"
install:
  - pip install -r requirements.txt
  - pip install pytest
  - pip install pytest-cov
  - pip install codecov

# Run the unit test
script:
  - coverage

# Push the results back to codecov
after_success:
  - codecov -t CODECOV_TOKEN
  - bash <(curl -s https://codecov.io/bash) -t CODECOV_TOKEN