language: python
python:
  - "3.7"
install:
  - pip install -r requirements.txt
  - pip install codecov

# Run the unit test
script:
  - pytest tests/test_*.py --doctest-modules --junitxml=junit/test-results.xml

# Push the results back to codecov
after_success:
  - python -m codecov -t CODECOV_TOKEN
  - bash <(curl -s https://codecov.io/bash) -t CODECOV_TOKEN