language: python
python:
  - "3.7"
install:
  - pip install -r requirements.txt
  - pip install codecov

# Run the unit test
script:
  - coverage run tests.py

# Push the results back to codecov
after_success:
  - codecov