language: python
dist: xenial
python:
  - "3.7"
install:
    - pip install -r requirements.txt
    # Install dependencies
    - pip install coverage pytest pytest-cov
    - python setup.py test

script:
    # Run tests
    - pytest tests/ --doctest-modules -o junit_family=xunit1 --junitxml=junit/test-results.xml --cov=hacker_rank --cov-report=xml --cov-report=html

    # Generate coverage report in XML format
    - coverage report -m

# Push the results back to codecov
after_success:
  - codecov
  - bash <(curl -s https://codecov.io/bash)